function renderParticipantTable(){var showResult=scoreTrackingEnabled(),head='<tr><th>Nr.</th><th>Start</th><th>Ende</th><th>Feld</th><th>Mannschaft A</th><th>Mannschaft B</th>'+(showResult?'<th>Ergebnis</th>':'')+'</tr>',base=normalizeTime(),dur=clampInt(durationInput.value,1,240,10),pause=clampInt(breakInput.value,0,240,5),rows='';participantScheduleHead.innerHTML=head;currentMatches.forEach(function(m){var s=matchStartMinute(m,base,dur,pause),e=s+dur;rows+='<tr data-home="'+esc(m.home)+'" data-away="'+esc(m.away)+'" data-key="'+esc(matchKey(m))+'"><td>'+m.no+'</td><td>'+fmt(s)+'</td><td>'+fmt(e)+'</td><td>Feld '+m.field+'</td><td>'+esc(m.home)+'</td><td>'+esc(m.away)+'</td>'+(showResult?'<td class="result-cell">'+resultText(m)+'</td>':'')+'</tr>';});participantTableBody.innerHTML=rows;}

function standingsRows(){var teams=getTeams(),stats={};teams.forEach(function(t){stats[t]={team:t,played:0,w:0,d:0,l:0,gf:0,ga:0,pts:0};});currentMatches.forEach(function(m){var s=scores[matchKey(m)];if(!s||s.home===null||s.home===undefined||s.away===null||s.away===undefined||!stats[m.home]||!stats[m.away])return;var h=stats[m.home],a=stats[m.away];h.played++;a.played++;h.gf+=s.home;h.ga+=s.away;a.gf+=s.away;a.ga+=s.home;if(s.home>s.away){h.w++;a.l++;h.pts+=3;}else if(s.home<s.away){a.w++;h.l++;a.pts+=3;}else{h.d++;a.d++;h.pts++;a.pts++;}});var arr=Object.keys(stats).map(function(k){return stats[k];});arr.sort(function(a,b){return b.pts-a.pts||((b.gf-b.ga)-(a.gf-a.ga))||b.gf-a.gf||a.team.localeCompare(b.team,'de');});return arr.map(function(s,i){var diff=s.gf-s.ga;return '<tr><td>'+(i+1)+'</td><td>'+esc(s.team)+'</td><td class="num">'+s.played+'</td><td class="num">'+s.w+'</td><td class="num">'+s.d+'</td><td class="num">'+s.l+'</td><td class="num">'+s.gf+':'+s.ga+'</td><td class="num">'+(diff>0?'+':'')+diff+'</td><td class="num"><strong>'+s.pts+'</strong></td></tr>';}).join('');}
function renderStandings(){var show=scoreTrackingEnabled();participantStandingsSection.classList.toggle('hidden',!show);adminStandingsSection.classList.toggle('hidden',!show);var rows=show?standingsRows():'';participantStandingsBody.innerHTML=rows;adminStandingsBody.innerHTML=rows;}

function updateSummaries(base,dur,pause,maxEnd){var teams=getTeams(),fields=clampInt(fieldCountInput.value,1,10,2);gamesSummary.textContent=currentMatches.length+(currentMatches.length===1?' Spiel':' Spiele');endSummary.textContent='Ende '+fmt(maxEnd)+' Uhr';document.getElementById('participantStart').textContent=fmt(base)+' Uhr';document.getElementById('participantDuration').textContent=dur+' Minuten';document.getElementById('participantBreak').textContent=pause+' Minuten';document.getElementById('participantFields').textContent=String(Math.min(fields,Math.max(1,Math.floor(teams.length/2))));document.getElementById('participantMode').textContent=gameModeSelect.value==='double'?'Hin- und Rückrunde':'Hinrunde';document.getElementById('participantGames').textContent=currentMatches.length+(currentMatches.length===1?' Spiel':' Spiele');document.getElementById('participantEnd').textContent='Ende '+fmt(maxEnd)+' Uhr';}

function renderAll(){updateTournamentTitle();updateRoundBreakVisibility();var teams=getTeams();updateFilters(teams);var base=normalizeTime();if(base===null){alert('Bitte eine gültige Startzeit auswählen.');return;}var dur=clampInt(durationInput.value,1,240,10),pause=clampInt(breakInput.value,0,240,5);durationInput.value=dur;breakInput.value=pause;normalizeRoundBreakInput();currentMatches=teams.length>=2?makeSchedule(teams):[];var maxEnd=base;currentMatches.forEach(function(m){maxEnd=Math.max(maxEnd,matchStartMinute(m,base,dur,pause)+dur);});updateSummaries(base,dur,pause,maxEnd);renderCards(participantCards,false);renderCards(adminCards,true);renderParticipantTable();renderStandings();adminScoreNote.textContent=scoreTrackingEnabled()?'Ergebnisse werden hier zentral gepflegt. Änderungen erscheinen sofort in der Teilnehmeransicht.':'Die Torerfassung ist aktuell deaktiviert.';applyParticipantFilter();applyAdminFilter();}

function applyFilter(container,tableBody,select,hint){var selected=select.value||'all',visible=0;container.querySelectorAll('.match-card').forEach(function(card){var ok=selected==='all'||card.dataset.home===selected||card.dataset.away===selected;card.classList.toggle('hidden',!ok);if(ok)visible++;});container.querySelectorAll('.slot-block').forEach(function(block){var has=Array.prototype.some.call(block.querySelectorAll('.match-card'),function(card){return !card.classList.contains('hidden');});block.classList.toggle('hidden',!has);});if(tableBody)tableBody.querySelectorAll('tr').forEach(function(row){var ok=selected==='all'||row.dataset.home===selected||row.dataset.away===selected;row.classList.toggle('hidden',!ok);});hint.textContent=visible+(visible===1?' Spiel sichtbar':' Spiele sichtbar');}
function applyParticipantFilter(){applyFilter(participantCards,participantTableBody,participantTeamFilter,participantCountHint);}
function applyAdminFilter(){applyFilter(adminCards,null,adminTeamFilter,adminCountHint);}

function parseScore(v){if(v==='')return null;var n=parseInt(v,10);if(isNaN(n)||n<0)return null;return Math.min(99,n);}
function updateScoreFromInput(input){var card=input.closest('.match-card'),key=card?card.dataset.key:'';if(!key)return;var homeInput=card.querySelector('[data-score-side="home"]'),awayInput=card.querySelector('[data-score-side="away"]'),home=parseScore(homeInput.value),away=parseScore(awayInput.value);homeInput.value=home===null?'':home;awayInput.value=away===null?'':away;if(home===null&&away===null)delete scores[key];else scores[key]={home:home,away:away};var display=card.querySelector('.public-result');if(display)display.textContent=(home!==null&&away!==null)?home+' : '+away:'– : –';renderCards(participantCards,false);renderParticipantTable();renderStandings();applyParticipantFilter();}

function currentState(){return {title:tournamentTitle(),teams:getTeams(),start:startTimeInput.value,duration:durationInput.value,breakMinutes:breakInput.value,roundBreakMinutes:roundBreakInput.value,fields:fieldCountInput.value,mode:gameModeSelect.value,scoreTracking:scoreTrackingEnabled(),scores:scores};}
function applyInitialState(){try{var el=document.getElementById('prefilledState'),raw=el?el.textContent.trim():'',state=raw?JSON.parse(raw):{};if(state.title)tournamentTitleInput.value=String(state.title).slice(0,80);if(state&&Array.isArray(state.teams)&&state.teams.length)setTeamRows(state.teams);if(state.start)startTimeInput.value=state.start;if(state.duration!==undefined)durationInput.value=state.duration;if(state.breakMinutes!==undefined)breakInput.value=state.breakMinutes;if(state.roundBreakMinutes!==undefined)roundBreakInput.value=state.roundBreakMinutes;if(state.fields!==undefined)fieldCountInput.value=state.fields;if(state.mode)gameModeSelect.value=state.mode;if(state.scoreTracking!==undefined)scoreTrackingInput.value=state.scoreTracking?'yes':'no';if(state.scores&&typeof state.scores==='object')scores=state.scores;}catch(e){console.warn('Vorgefüllter Zustand konnte nicht geladen werden.',e);}}
